Add support for IngressClass resources
nginxinc/kubernetes-ingress pull request #1133
Opened 2020-09-09 04:07 UTC by lucacome

Supporting `IngressClass` resource and `ingressClassName` for versions of k8s >= 1.18.

When using version of k8s >= the `use-ingress-class-only` is now ignored and the Ingress Controller will only handle resources with the appropriate class set.

2020-09-09 10:16 UTC, LorcanMcVeigh approved these changes

2020-09-09 11:03 UTC, Dean-Coakley reviewed
@lucacome This looks great!

Just one thing to make you aware of, is that you can set a compatible kubernetes version in your Chart.yaml. https://helm.sh/docs/topics/charts/#the-chartyaml-file

Example: `kubeVersion: 1.15-1.19`.

This would reject the installation of a helm release at the helm client level. I think this could be a nice improvement to include as it shortens the feedback loop for a user. (They don't have to install incompatible resources into their cluster to see logs that their cluster is incompatible.)
```
$ helm install test deployments/helm-chart
Error: chart requires kubeVersion: 1.15-1.19 which is incompatible with Kubernetes v1.14.0

$ helm ls
$
```

Feel free to ignore, we can always refer back to: https://docs.nginx.com/nginx-ingress-controller/technical-specifications/#supported-kubernetes-versions and hope most users read that.

2020-09-09 18:19 UTC, pleshakov requested changes
Hi @lucacome 

Please see my comments and suggestions. Most of them about docs. Looks good overall.

Additionally,

(1) We're changing behavior for VirtualServer/VirtualServerRoutes, right? Previously, if `"-use-ingress-class-only" was enabled, the IC would ignore VS/VSRs with empty class. Now it won't ignore them. If that's the case, could you add the change label to the PR? We will also need to document that change in the changelog.

(2) Could you include in the description that you're fixing this https://github.com/nginxinc/kubernetes-ingress/issues/924 ?

2020-09-09 18:19 UTC, pleshakov commented on docs-web/installation/running-multiple-ingress-controllers.md
>  ### Configuring Ingress Class
You need to update the note in this section. Perhaps something like this? (please double check it, I might not have got it right with VirtualServers)

**Notes**: 
* For Kubernetes < 1.18,  if the class is not set in an Ingress configuration resource, the Ingress Controller will handle the resource. This is controlled via the `-use-ingress-class-only` argument. 
* For Kubernetes >= 1.18,  if the class is not set in an Ingress resource, Kubernetes will set it to the class of the default Ingress Controller. To make the Ingress Controller the default one, the `ingressclass.kubernetes.io/is-default-class` must be set on the IngressClass resource. See the Step 3 *Create an IngressClass resource* of the [Create Common Resources](https://deploy-preview-1133--nginx-kubernetes-ingress.netlify.app/nginx-ingress-controller/installation/installation-with-manifests/#create-common-resources) section.
* For VirtualServer and VirtualServerRoute resources, the Ingress Controller will always handle resources with an empty  class.

2020-09-09 18:19 UTC, pleshakov commented on docs-web/installation/installation-with-helm.md
> -     - A class of the Ingress controller. The Ingress controller only processes Ingress resources that belong to its class - i.e. have the annotation ``"kubernetes.io/ingress.class"``  or the ``"ingr
the preview for this table wasn't generated -- https://deploy-preview-1133--nginx-kubernetes-ingress.netlify.app/nginx-ingress-controller/installation/installation-with-helm/
I suspect some errors

2020-09-09 18:19 UTC, pleshakov commented on deployments/helm-chart/Chart.yaml
> +kubeVersion: ">= 1.15.0"
In the main.go, we support 1.14. Here in helm, we don't support it. Was it intentional?  🤔

2020-09-09 20:10 UTC, Dean-Coakley approved these changes
LGTM pending https://github.com/nginxinc/kubernetes-ingress/pull/1133#discussion_r485818176

(Sorry if my example misled you @lucacome 😓 )

2020-09-10 17:04 UTC, pleshakov approved these changes
@lucacome  looks good. Could you fix the mentioned link problems before merging?

2020-09-10 17:04 UTC, pleshakov commented on docs-web/installation/running-multiple-ingress-controllers.md
> +* For Kubernetes >= 1.18, if the class is not set in an Ingress resource, Kubernetes will set it to the class of the default Ingress Controller. To make the Ingress Controller the default one, the `i
same problem with an absolute link

2020-09-10 18:03 UTC, merged