Add Grafana dashboard for Plus
nginxinc/kubernetes-ingress pull request #1194
Opened 2020-10-19 11:08 UTC by LorcanMcVeigh

### Proposed changes
Add a Grafana dashboard for plus metrics.

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

- [x] I have read the [CONTRIBUTING](https://github.com/nginxinc/kubernetes-ingress/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that all unit tests pass after adding my changes
- [x] I have updated necessary documentation
- [x] I have rebased my branch onto master
- [x] I will ensure my PR is targeting the master branch and pulling from my branch from my own fork

2020-10-19 19:23 UTC, pleshakov requested changes
Hi @LorcanMcVeigh 

The PR doesn't add the docs unfortunately. You can take a look at https://deploy-preview-1194--nginx-kubernetes-ingress.netlify.app/  -- there are no docs there.

I like the overall structure and content. However, there are a few problems. Please see my suggestion.

Additionally:
* I suggest moving this folder to the root repo folder, similar to this https://github.com/nginxinc/nginx-prometheus-exporter/tree/master/grafana . So it will have both the dashboard and the README. Having the dashboard and readme there will also allow people to easily use the master version of the dashboard without waiting for a new release.
* In the docs, I suggest adding adding a Graphana section here https://deploy-preview-1194--nginx-kubernetes-ingress.netlify.app/nginx-ingress-controller/logging-and-monitoring/prometheus/  that will reference the dashboard:
 
## Enabling Metrics
. . .
## Available Metrics
. . .
## Graphana Dashboard 

You can visualize the Prometheus metrics using the Graphana dashboard from our [GitHub repo](). The dashboard is only available for NGINX Plus.

2020-10-20 07:52 UTC, Dean-Coakley commented on docs-web/logging-and-monitoring/grafana/README.md
> +    * Reloads ( `nginx_reloads_total`). This graph shows the total times Nginx has reloaded.
```suggestion
    * Reloads (`nginx_reloads_total`). This graph shows the total times Nginx has reloaded.
```

2020-10-20 07:52 UTC, Dean-Coakley commented on docs-web/logging-and-monitoring/grafana/README.md
> +    * Netowrk I/O (`nginxplus_server_zone_received` and `nginxplus_server_zone_sent`). This graphs shows the traffic sent and recieved by the Ingress Controller.
```suggestion
    * Network I/O (`nginxplus_server_zone_received` and `nginxplus_server_zone_sent`). This graphs shows the traffic sent and received by the Ingress Controller.
```

2020-10-20 07:52 UTC, Dean-Coakley commented on docs-web/logging-and-monitoring/grafana/README.md
> +    * HTTP Request Volume (`nginxplus_http_requests_total`). This graphs shows the total number of HTTP requests recieved by the Ingress Controller.
```suggestion
    * HTTP Request Volume (`nginxplus_http_requests_total`). This graphs shows the total number of HTTP requests received by the Ingress Controller.
```

2020-10-20 07:58 UTC, Dean-Coakley commented on docs-web/logging-and-monitoring/grafana/NGINXPlusICDashboard.json
> +          "title": "Sucess Rates Over Time",
```suggestion
          "title": "Success Rates Over Time",
```

2020-10-20 07:58 UTC, Dean-Coakley commented on docs-web/logging-and-monitoring/grafana/NGINXPlusICDashboard.json
> +      "description": "Bytes received from clients and  sent to clients.",
```suggestion
      "description": "Bytes received from clients and sent to clients.",
```

2020-10-20 09:50 UTC, martialonline approved these changes
👍

2020-10-20 09:50 UTC, vepatel approved these changes

2020-10-20 09:51 UTC, merged