Release 1.10.0 in master
nginxinc/kubernetes-ingress pull request #1325
Opened 2021-01-25 15:27 UTC by mikestephen

### Proposed changes
Describe the use case and detail of the change. If this PR addresses an issue on GitHub, make sure to include a link to that issue here in this description (not in the title of the PR).

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

- [x] I have read the [CONTRIBUTING](https://github.com/nginxinc/kubernetes-ingress/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that all unit tests pass after adding my changes
- [x] I have updated necessary documentation
- [x] I have rebased my branch onto master
- [x] I will ensure my PR is targeting the master branch and pulling from my branch from my own fork

2021-01-25 17:54 UTC, lucacome requested changes
I think we need to update https://github.com/nginxinc/kubernetes-ingress/blob/master/docs-web/technical-specifications.md#L30 too

2021-01-25 21:55 UTC, pleshakov approved these changes
looks good to me, provided that the changelogs will be updated to match the finalized changelogs in the release PR

re @lucacome comments, putting edge versions as tags would work there

2021-01-26 11:52 UTC, Dean-Coakley approved these changes

2021-01-26 11:52 UTC, Dean-Coakley commented on docs-web/technical-specifications.md
> +      - ``nginx/nginx-ingress:edge``
This page should reference the latest production ready release available:
```suggestion
      - ``nginx/nginx-ingress:1.10.0``
```

2021-01-26 11:52 UTC, Dean-Coakley commented on docs-web/technical-specifications.md
> +      - ``nginx/nginx-ingress:edge-alpine``
```suggestion
      - ``nginx/nginx-ingress:1.10.0-alpine``
```

2021-01-26 11:52 UTC, Dean-Coakley commented on docs-web/technical-specifications.md
> +      - ``nginx/nginx-ingress:edge-ubi``
```suggestion
      - ``nginx/nginx-ingress:1.10.0-ubi``
```

2021-01-26 11:52 UTC, Dean-Coakley commented on docs-web/releases.md
> +### NGINX Ingress Controller 1.10.0
For consistency with 1.9.0:

```suggestion
## NGINX Ingress Controller 1.10.0
```

However, I don't see any difference in resulting page: https://deploy-preview-1325--nginx-kubernetes-ingress.netlify.app/nginx-ingress-controller/releases/

2021-01-26 16:33 UTC, lucacome approved these changes

2021-01-26 16:41 UTC, merged