Fix ungraceful shutdown of NGINX
nginxinc/kubernetes-ingress pull request #1501
Opened 2021-04-02 22:39 UTC by pleshakov

To shutdown the IC container, the container runtime sends a signal
to it (SIGTERM by default). The IC handles the SIGTERM signal - after
receiving it, it will gracefully shutdown NGINX and exit.

The termination signal can be customized in the Dockerfile via
STOPSIGNAL. In https://github.com/nginxinc/docker-nginx/commit/3fb70ddd7094c1fdd50cc83d432643dc10ab6243
the STOPSIGNAL in the NGINX base images was changed from SIGTERM to
SIGQUIT. Because the IC didn't register a handler for SIGQUIT, the IC
would terminate immediately with a stack dump. As a result, the NGINX
wasn't gracefully shutdown, meaning any inflight requests were aborted.

This commits explicitly configures STOPSIGNAL to SIGTERM in the
Dockerfiles, which overrides any value set in the base images. This
restores graceful shutdown of NGINX.

The bug only affected NGINX images, because NGINX Plus images use
different base images without configured STOPSIGNAL.

while not requred, I added STOPSIGNAL to build/DockerfileWithAppProtectForPlusForOpenShift for consistency

2021-04-02 22:52 UTC, lucacome commented
Wouldn't it be better to handle the SIGQUIT too in the code, so we don't differ too much from the base image?

2021-04-05 15:51 UTC, pleshakov commented
@lucacome since we have control (in the Dockerfile) over what signal is sent to IC, I don't see a point of handling multiple signals, when handling `SIGTERM` is enough

2021-04-05 16:08 UTC, lucacome commented
You linked a document saying that not every runtime will respect the `STOPSIGNAL`, I don't see the harm of handling multiple signals directly in the code where we have control over things.

2021-04-05 16:13 UTC, pleshakov commented
@lucacome could you give an example when a runtime will send a SIGQUIT?

2021-04-05 19:47 UTC, lucacome commented on build/Dockerfile
> +STOPSIGNAL SIGTERM
you can just have the `STOPSIGNAL` once if you put it in `files` like on line 288

2021-04-05 19:48 UTC, lucacome requested changes

2021-04-05 19:48 UTC, lucacome commented on build/Dockerfile
> +STOPSIGNAL SIGTERM
you can just have the `STOPSIGNAL` once if you put it in files like on line 288

2021-06-14 19:23 UTC, pleshakov commented
rebased against the master branch

2021-06-15 08:35 UTC, soneillf5 approved these changes

2021-06-15 13:44 UTC, ciarams87 approved these changes

2021-06-15 17:18 UTC, merged