WIP: Update repo files for release 1.11.1
nginxinc/kubernetes-ingress pull request #1515
Opened 2021-04-06 11:44 UTC by ciarams87

### Proposed changes
Describe the use case and detail of the change. If this PR addresses an issue on GitHub, make sure to include a link to that issue here in this description (not in the title of the PR).

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

- [ ] I have read the [CONTRIBUTING](https://github.com/nginxinc/kubernetes-ingress/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that all unit tests pass after adding my changes
- [ ] I have updated necessary documentation
- [ ] I have rebased my branch onto master
- [ ] I will ensure my PR is targeting the master branch and pulling from my branch from my own fork

2021-04-06 11:55 UTC, soneillf5 approved these changes

2021-04-07 02:42 UTC, lucacome requested changes

2021-04-07 02:42 UTC, lucacome commented on CHANGELOG.md
> +### 1.11.1
I think we should have the same message as `1.11.0` about automated list of changes

2021-04-08 10:23 UTC, vepatel approved these changes

2021-04-08 10:49 UTC, merged