Add container scanning for OSS images
nginxinc/kubernetes-ingress pull request #1580
Opened 2021-05-07 13:47 UTC by ciarams87

### Proposed changes
Add trivy container scanning for OSS images. Scanning of the Plus and App Protect images will be done separately in GitLab.

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

- [x] I have read the [CONTRIBUTING](https://github.com/nginxinc/kubernetes-ingress/blob/master/CONTRIBUTING.md) doc
- [x] I have rebased my branch onto master

2021-05-07 23:39 UTC, lucacome requested changes
Do we need to build the images again? Can't it just be a step in one of the other builds?

2021-05-07 23:39 UTC, lucacome commented on .github/workflows/edge.yml
> +          severity: 'CRITICAL,HIGH'
should we also include `LOW` and `MEDIUM`? I think if we enable `ignore-unfixed: true` it makes sense to have them all.

2021-05-07 23:39 UTC, lucacome commented on .github/workflows/edge.yml
> +          severity: 'CRITICAL,HIGH'
we should add `ignore-unfixed: true` since if they're not fixed upstream there's not much we can do.

2021-05-10 10:37 UTC, ciarams87 commented
> Do we need to build the images again? Can't it just be a step in one of the other builds?

It could just be a step in another build, but having it as a separate stage runs these jobs concurrently with the other helm and smoke tests, so it doesn't take any longer, and I think it's easier to follow this way.

2021-05-11 18:51 UTC, pleshakov approved these changes

2021-05-12 08:44 UTC, merged