docs: Add AWS Marketplace image IAM instructions
nginxinc/kubernetes-ingress pull request #1932
Opened 2021-09-07 08:17 UTC by ciarams87

### Proposed changes
Add AWS Marketplace image IAM instructions

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

- [ ] I have read the [CONTRIBUTING](https://github.com/nginxinc/kubernetes-ingress/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that all unit tests pass after adding my changes
- [ ] I have updated necessary documentation
- [ ] I have rebased my branch onto master
- [ ] I will ensure my PR is targeting the master branch and pulling from my branch from my own fork

2021-09-07 08:30 UTC, vepatel approved these changes

2021-09-07 10:35 UTC, tomasohaodha requested changes

2021-09-07 10:35 UTC, tomasohaodha commented on docs/content/installation/using-aws-marketplace-image.md
> +1. Ensure you have a working AWS EKS cluster. If you do not have a EKS cluster, you can create one using either the AWS console, or using the AWS tool eksctl. See [this guide](https://docs.aws.amazon
The link doesn't work. Perhaps this is the intended one? (case sensitive it seems)
https://docs.aws.amazon.com/eks/latest/userguide/getting-started-eksctl.html

2021-09-08 19:03 UTC, pleshakov approved these changes

2021-09-09 07:47 UTC, merged