Integrate NGINX App Protect DoS
nginxinc/kubernetes-ingress pull request #2004
Opened 2021-09-23 22:54 UTC by pleshakov

This PR brings support for NGINX App Protect DoS

2021-09-30 11:27 UTC, pasmant commented on Makefile
> +.PHONY: app-protect-dos-arb
removed

2021-09-30 12:38 UTC, pasmant commented on build/Dockerfile
> +RUN mkdir -p /etc/nginx/dos/policies /etc/nginx/dos/logconfs /var/lib/nginx /etc/nginx/secrets /etc/nginx/stream-conf.d \
Done

2021-09-30 12:41 UTC, pasmant commented on cmd/nginx-ingress/main.go
> +		nginxManager.AppProtectDosAgentStart(aPPDosAgentDone, *nginxDebug || cfgParams.AppProtectDosDebug, cfgParams.AppProtectDosMaxDaemon, cfgParams.AppProtectDosMaxWorkers, cfgParams.AppProtectDosMemory
Will remove the comment

2021-09-30 12:46 UTC, pasmant commented on internal/configs/version1/nginx-plus.ingress.tmpl
> +	app_protect_enable {{$server.AppProtectEnable}};{{- end}}
Will fix it, no need to add this at the first place

2021-09-30 12:49 UTC, pasmant commented on build/Dockerfile
> +    && apt-get -y install app-protect-dos
done

2021-09-30 12:52 UTC, pasmant commented on internal/configs/version1/nginx-plus.ingress.tmpl
> +    {{- end}}
done

2021-09-30 12:57 UTC, pasmant commented on internal/configs/annotations.go
> +	"appprotectdos.f5.com/app_protect_dos_security_log_destination": true,
Here is blacklist with underscore _ (not like the const at the top)

2021-09-30 13:00 UTC, pasmant commented on internal/configs/configurator.go
> +// DeleteAppProtectLogConf updates Ingresses and VirtualServers that use AP Log Configuration after that policy is deleted
done

2021-09-30 13:20 UTC, pasmant commented on internal/configs/annotations.go
> +		if appProtectDosEnable, exists, err := GetMapKeyAsBool(ingEx.Ingress.Annotations, "appprotectdos.f5.com/app-protect-dos-enable", ingEx.Ingress); exists {
the annotations here not appear in the top. the top const here used in other file

2021-09-30 14:42 UTC, aknot242 commented on internal/configs/version2/nginx-plus.virtualserver.tmpl
> +        app_protect_dos_security_log {{ .ApDosLogConf }};
@pleshakov the combination of both logs should be used if the customer wants to use the [NAP DoS dashboard](https://github.com/f5devcentral/nap-dos-elk-dashboards#nginx-app-protect-dos-configuration). Some of the logs are provided by nginx access logs over TCP (using custom variables), and some of the logs are from DoS itself (over UDP). There may use cases other than the dashboard.

2021-10-01 01:09 UTC, pleshakov commented on internal/configs/configurator.go
> +	if vsEx.ApDosPolRefs != nil {
https://github.com/nginxinc/kubernetes-ingress/pull/2032

2021-10-03 07:52 UTC, pasmant commented on internal/k8s/appprotectdos/app_protect_dos_configuration.go
> +	DosPolicies map[string]*DosPolicyEx
Make them private

2021-10-03 07:59 UTC, pasmant commented on internal/k8s/appprotectdos/app_protect_dos_resources.go
> +	if (len(name) > MaxNameLength) {
NGINX module make only length validation on the name
The directive not support variables
For the example above the vs_name will be hello$host.
Took from admd:
VS Stats:
vs_name:                                 hello$host
vs_hash:                                 3751576534
vs_id:                                   1
vs_uri:                                  webapp.example.com

2021-10-03 08:05 UTC, pasmant commented on internal/k8s/controller.go
> +				warnings, deleteErr := lbc.configurator.DeleteAppProtectLogConf(impl.Obj, namespace+"/"+name, resourceExes.IngressExes, resourceExes.MergeableIngresses, resourceExes.VirtualServerExes)
Fix, call the DeleteAppProtectDosLogConf

2021-10-03 08:19 UTC, pasmant commented on internal/k8s/appprotectdos/app_protect_dos_resources.go
> +	_, err := url.Parse(monitor)
NGINX module not make any validation
The directive not support variables
For the example above the vs_name will be hello$host.
Took from admd:
VS Stats:
```
vs_name:                                 hello$host
vs_hash:                                 3751576534
vs_id:                                   1
vs_uri:                                  hello$host
```

2021-10-03 09:41 UTC, pasmant commented on deployments/helm-chart-dos-arbitrator/values.yaml
> +    ## The tag of the Ingress controller image.
done

2021-10-03 09:42 UTC, pasmant commented on deployments/helm-chart-dos-arbitrator/values.yaml
> +    ## The pull policy for the Ingress controller image.
Done

2021-10-03 11:11 UTC, pasmant commented on internal/k8s/validation_test.go
> +			msg: "valid app-protect-dos-security-log-destination annotation",
done

2021-10-03 11:19 UTC, pasmant commented on internal/k8s/validation.go
> +		return append(allErrs, field.Invalid(context.fieldPath, context.value, fmt.Sprintf("annotation value: %v is not qualified name", context.value)))
done also for unit test

2021-10-03 11:27 UTC, pasmant commented on deployments/helm-chart-dos-arbitrator/templates/controller-appprotect-dos-arb.yaml
> +apiVersion: apps/v1
done, make yaml file to deployment and one for the svc

2021-10-03 12:03 UTC, pasmant commented on internal/configs/version1/nginx-plus.tmpl
> +    log_format log_dos '{{.AppProtectDosLogFormat}}';
Add default value for log_dos

2021-10-03 12:42 UTC, pasmant commented on deployments/helm-chart-dos-arbitrator/Chart.yaml
> +appVersion: 1.12.1
done

2021-10-03 13:33 UTC, pasmant commented on pkg/apis/configuration/validation/policy.go
> +func validateBados(bados *v1.Bados, fieldPath *field.Path) field.ErrorList {
done

2021-10-03 13:33 UTC, pasmant commented on pkg/apis/configuration/validation/policy.go
> +    if bados.DosAccessLogDest != "" {
done

2021-10-03 13:33 UTC, pasmant commented on pkg/apis/configuration/validation/policy.go
> +	if spec.Bados != nil {
done, also added for TestValidatePolicy

2021-10-04 16:21 UTC, pleshakov commented on internal/configs/configurator.go
> +	if vsEx.ApDosPolRefs != nil {
merged and done

2021-10-04 18:01 UTC, pleshakov commented on internal/configs/configurator_test.go
> +func TestUpdateApDosResources(t *testing.T) {
this is no longer relevant after the refactoring done in https://github.com/nginxinc/kubernetes-ingress/pull/2032

2021-10-04 19:28 UTC, pleshakov commented on internal/configs/annotations.go
> +	"appprotectdos.f5.com/app_protect_dos_security_log_destination": true,
oh, this is a bug. We will fix the NAP annotations separately. Could you fix the DOS-related annotations?

2021-10-04 19:34 UTC, pleshakov commented on internal/k8s/appprotectdos/app_protect_dos_resources.go
> +	if (len(name) > MaxNameLength) {
in this case, on top of the max length validation, we need to insure that the value inside cannot escape "..." string, which can lead to a failed NGINX reload, which would be similar to https://github.com/nginxinc/kubernetes-ingress/blob/4688555a3e0337a9fbac4053d159d49f232d0940/pkg/apis/configuration/validation/virtualserver.go#L796-L799

2021-10-04 23:05 UTC, pleshakov commented on internal/configs/configurator.go
> +func (cnf *Configurator) DeleteAppProtectLogConf(resource *unstructured.Unstructured, logConfNamespaceName string, ingExes []*IngressEx, mergeableIngresses []*MergeableIngresses, vsExes []*VirtualSer
addressed in https://github.com/nginxinc/kubernetes-ingress/pull/2036

2021-10-04 23:05 UTC, pleshakov commented on internal/configs/configurator.go
> +func (cnf *Configurator) AddOrUpdateAppProtectResource(resource *unstructured.Unstructured, ingExes []*IngressEx, mergeableIngresses []*MergeableIngresses, vsExes []*VirtualServerEx, reload bool) (Wa
addressed in https://github.com/nginxinc/kubernetes-ingress/pull/2036

2021-10-04 23:22 UTC, pleshakov commented on internal/configs/annotations.go
> +		if appProtectDosEnable, exists, err := GetMapKeyAsBool(ingEx.Ingress.Annotations, "appprotectdos.f5.com/app-protect-dos-enable", ingEx.Ingress); exists {
ok. please disregard this request

2021-10-04 23:29 UTC, pleshakov commented on internal/configs/annotations.go
> +	"appprotectdos.f5.com/app_protect_dos_security_log_destination": true,
addressed in https://github.com/nginxinc/kubernetes-ingress/pull/2037

2021-10-05 11:24 UTC, pasmant commented on internal/k8s/appprotectdos/app_protect_dos_resources.go
> +const MaxNameLength = 64
Add doc inside the policy-resource.md and in advanced-configuration-with-annotations.md

2021-10-10 06:45 UTC, pasmant commented on internal/k8s/appprotectdos/app_protect_dos_resources.go
> +	if (len(name) > MaxNameLength) {
Add new validation

2021-10-10 06:45 UTC, pasmant commented on internal/k8s/appprotectdos/app_protect_dos_resources.go
> +	_, err := url.Parse(monitor)
Add new validation

2021-10-10 06:47 UTC, pasmant commented on internal/configs/version1/nginx-plus.tmpl
> +    log_format log_dos '{{.AppProtectDosLogFormat}}';
Will fix in PR #1999

2021-10-12 11:04 UTC, pasmant commented on internal/k8s/appprotectdos/app_protect_dos_resources.go
> +	if (len(name) > MaxNameLength) {
https://github.com/nginxinc/kubernetes-ingress/pull/2076

2021-10-21 17:11 UTC, aknot242 requested changes

2021-10-21 17:11 UTC, aknot242 commented on pkg/apis/configuration/validation/dos.go
> +	_, err := url.Parse(monitor)
In NAP DoS 2.0, the `app_protect_dos_monitor` directive has changed. It now supports `uri`, `protocol` and `timeout` fields. In gRPC streaming use cases, the `uri` and `protocol` fields are required to be set. Therefore, validation by simply parsing as a URL will no longer be sufficient. http://localhost:1313/nginx-app-protect-dos/directives-and-policy/learn-about-directives-and-policy/#for-nginx-app-protect-dos-v2

2021-12-03 11:50 UTC, soneillf5 commented
Closing this pull request and re-opening it. We've addressed the comments made and would like a less noisy PR to do a fresh review.

2021-12-03 11:50 UTC, closed without merging