Create SECURITY.md
nginxinc/kubernetes-ingress pull request #2475
Opened 2022-03-03 23:42 UTC by lucacome

Adds Security Policy

2022-03-04 16:53 UTC, brianehlert commented on SECURITY.md
> +| < 1.6.3   | :x:                |
Is it possible to extend the version support table in the tech specs to include this?  So that this table also is not in need of update each release?

2022-03-09 13:39 UTC, tomasohaodha requested changes

2022-03-09 21:56 UTC, ciarams87 approved these changes

2022-03-09 23:01 UTC, GirishF5 approved these changes

2022-03-09 23:04 UTC, merged