Add minReadySeconds & strategy support
nginxinc/kubernetes-ingress pull request #2672
Opened 2022-05-10 07:54 UTC by cmk-pcs

### Proposed changes
Adding support for deployment strategy and minReadySeconds to helm chart.

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

- [x] I have read the [CONTRIBUTING](https://github.com/nginxinc/kubernetes-ingress/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that all unit tests pass after adding my changes
- [x] I have updated necessary documentation
- [x] I have rebased my branch onto main
- [x] I will ensure my PR is targeting the main branch and pulling from my branch from my own fork

2022-05-11 17:22 UTC, cmk-pcs commented
> @cmk-pcs Could you please open a corresponding issue to help us track your PR? Thank you!

Thanks, added: #2677

2022-05-13 01:06 UTC, lucacome requested changes
Hi @cmk-pcs 

Thanks for the PR! Would you mind also adding the new fields as a comment in `deployments/helm-chart/values.yaml`?

2022-05-16 18:23 UTC, lucacome requested changes

2022-05-16 18:23 UTC, lucacome commented on deployments/helm-chart/templates/controller-daemonset.yaml
> +  strategy:
```suggestion
  updateStrategy:
```

2022-05-17 15:39 UTC, lucacome approved these changes

2022-05-18 14:54 UTC, merged