Sanitize nginx.com/jwt-token
nginxinc/kubernetes-ingress pull request #2774
Opened 2022-06-17 19:25 UTC by haywoodsh

### Proposed changes
Sanitize nginx.com/jwt-token ingress annotation to disallow escape characters.

### Checklist
- [x] I have read the [CONTRIBUTING](https://github.com/nginxinc/kubernetes-ingress/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that all unit tests pass after adding my changes
- [x] I have updated necessary documentation
- [x] I have rebased my branch onto main
- [x] I will ensure my PR is targeting the main branch and pulling from my branch from my own fork

2022-06-20 20:10 UTC, jjngx approved these changes
👍🏻

2022-06-21 11:42 UTC, shaun-nx approved these changes

2022-06-21 13:51 UTC, shaun-nx requested changes
The docs page needs toe be updated in`docs/content/configuration/ingress-resources/advanced-configuration-with-annotations.md`

2022-06-21 14:32 UTC, shaun-nx approved these changes
Re-approved based on conversation

2022-06-21 22:32 UTC, merged