Add initialDelaySeconds to helm charts
nginxinc/kubernetes-ingress pull request #2854
Opened 2022-07-14 15:25 UTC by aknot242

### Proposed changes
Adds initialDelaySeconds for readiness probe to Helm charts. Addresses #2850 
Additionally, addresses a few template formatting issues.

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

- [X] I have read the [CONTRIBUTING](https://github.com/nginxinc/kubernetes-ingress/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that all unit tests pass after adding my changes
- [X] I have updated necessary documentation
- [ ] I have rebased my branch onto main
- [X] I will ensure my PR is targeting the main branch and pulling from my branch from my own fork

2022-07-15 21:46 UTC, lucacome requested changes

2022-07-15 22:23 UTC, aknot242 commented on deployments/helm-chart/templates/controller-daemonset.yaml
> +          - -ready-initial-delay-seconds={{ .Values.controller.readyStatus.initialDelaySeconds }}
good catch. removed.

2022-07-15 22:23 UTC, aknot242 commented on deployments/helm-chart/templates/controller-deployment.yaml
> +          - -ready-initial-delay-seconds={{ .Values.controller.readyStatus.initialDelaySeconds }}
good catch. removed.

2022-08-29 16:44 UTC, lucacome approved these changes

2022-08-29 21:47 UTC, haywoodsh approved these changes

2022-08-29 23:06 UTC, merged