Apdoslogconf will warning case format is not splunk
nginxinc/kubernetes-ingress pull request #2991
Opened 2022-08-31 08:31 UTC by pasmant

### Proposed changes
Describe the use case and detail of the change. If this PR addresses an issue on GitHub, make sure to include a link to that issue here in this description (not in the title of the PR).

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

- [ ] I have read the [CONTRIBUTING](https://github.com/nginxinc/kubernetes-ingress/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that all unit tests pass after adding my changes
- [ ] I have updated necessary documentation
- [ ] I have rebased my branch onto main
- [ ] I will ensure my PR is targeting the main branch and pulling from my branch from my own fork

2022-09-23 07:54 UTC, jjngx approved these changes

2022-09-23 17:38 UTC, lucacome requested changes

2022-09-23 17:38 UTC, lucacome commented on pkg/apis/dos/validation/dos.go
> +		msg := "Content field doesn't supported, use splunk format."
```suggestion
		msg := "the content field is not supported, defaulting to splunk format."
```

2022-09-29 06:39 UTC, pasmant commented on pkg/apis/dos/validation/dos.go
> +		msg := "Content field doesn't supported, use splunk format."
Change warning

2022-09-29 12:03 UTC, Jcahilltorre commented on pkg/apis/dos/validation/dos.go
> +		msg := "the content field is not supported, defaulting to splunk format."
```suggestion
		msg := "the Content field is not supported, defaulting to splunk format."
```

2022-09-29 12:03 UTC, Jcahilltorre approved these changes

2022-09-29 15:53 UTC, lucacome commented on internal/k8s/appprotectdos/app_protect_dos_configuration_test.go
> +				ErrorMsg: "the content field is not supported, defaulting to splunk format.",
```suggestion
				ErrorMsg: "the Content field is not supported, defaulting to splunk format.",
```

2022-09-29 16:53 UTC, lucacome approved these changes

2022-09-29 16:53 UTC, merged