Add lifecycle for controller container to helm chart
nginxinc/kubernetes-ingress pull request #3005
Opened 2022-09-02 13:19 UTC by coolbry95

### Proposed changes
Adding lifecycle to controller container. #267

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

- [x] I have read the [CONTRIBUTING](https://github.com/nginxinc/kubernetes-ingress/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that all unit tests pass after adding my changes
- [x] I have updated necessary documentation
- [x] I have rebased my branch onto main
- [x] I will ensure my PR is targeting the main branch and pulling from my branch from my own fork

2022-09-09 01:58 UTC, lucacome requested changes

2022-09-09 01:58 UTC, lucacome commented on deployments/helm-chart/templates/controller-daemonset.yaml
> +{{ toYaml .Values.controller.lifecycle | indent 8 }}
```suggestion
        lifecycle:
{{ toYaml .Values.controller.lifecycle | indent 10 }}
```

2022-09-09 01:58 UTC, lucacome commented on deployments/helm-chart/templates/controller-deployment.yaml
> +{{ toYaml .Values.controller.lifecycle | indent 8 }}
```suggestion
        lifecycle:
{{ toYaml .Values.controller.lifecycle | indent 10 }}
```

2022-09-09 23:10 UTC, lucacome approved these changes
Small change, but LGTM!

2022-09-09 23:10 UTC, lucacome commented on deployments/helm-chart/templates/controller-daemonset.yaml
> +{{- end -}}
```suggestion
{{- end }}
```

2022-09-09 23:10 UTC, lucacome commented on deployments/helm-chart/templates/controller-deployment.yaml
> +{{- end -}}
```suggestion
{{- end }}
```

2022-09-12 16:11 UTC, vepatel approved these changes

2022-09-12 16:39 UTC, jjngx approved these changes

2022-09-13 17:43 UTC, coolbry95 commented
Is there anything left to do here or can we merge this?

2022-09-19 19:29 UTC, merged