Remove deprecated kubernetes.io/ingress.class from examples and tests
nginxinc/kubernetes-ingress pull request #3029
Opened 2022-09-09 18:31 UTC by lucacome

Replaces `kubernetes.io/ingress.class` with  `ingressClassName`.

Opening it as a draft as I'm not sure if we need to add something to the examples to call out the need to deploy the ingressClass. It's already called out in the https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-manifests/ and we deploy it automatically with `helm`

2022-09-12 16:37 UTC, jjngx approved these changes

2022-09-13 15:39 UTC, vepatel commented
@lucacome can we do it for docs only first? some tests are breaking because of this change.

2022-09-13 19:57 UTC, tomasohaodha requested changes
Are the first two files really part of this PR? If not can they go into their own PR?

2022-09-19 15:31 UTC, tomasohaodha commented
Hi Luca are you going to remove the non-relevant files (as discussed last week)?

2022-09-23 16:44 UTC, tomasohaodha approved these changes

2022-09-23 16:46 UTC, merged