Update helloworld grpc generated file
nginxinc/kubernetes-ingress pull request #3220
Opened 2022-11-03 19:36 UTC by lucacome

Regenerated hello world pb2

2022-11-04 11:32 UTC, tomasohaodha requested changes
Can you please add more detail to the PR. "Regenerated hello world pb2" is not helpful to devs who do not already have context. Thanks.

2022-11-05 00:10 UTC, lucacome commented
@tomasohaodha updated the description

2022-11-07 10:31 UTC, ciarams87 approved these changes

2022-11-07 10:41 UTC, tomasohaodha approved these changes

2022-11-07 10:42 UTC, tomasohaodha commented
> @tomasohaodha updated the description

@lucacome Thanks!

2022-11-07 17:29 UTC, merged