DoS Status
nginxinc/kubernetes-ingress pull request #3379
Opened 2022-12-20 08:20 UTC by pasmant

Add for DoS the dashboard page and api, in the case 'nginxStatus' cli argument is enable.

2022-12-21 00:25 UTC, lucacome requested changes

2022-12-21 00:25 UTC, lucacome commented on docs/content/logging-and-monitoring/status-page.md
> +NGINX App Protect Dos comes with a [dashboard](https://docs.nginx.com/nginx-app-protect-dos/monitoring/live-activity-monitoring/)  that shows the status and information of the protected objects.
```suggestion
NGINX App Protect DoS comes with a [dashboard](https://docs.nginx.com/nginx-app-protect-dos/monitoring/live-activity-monitoring/) that shows the status and information of the protected objects.
```

2022-12-21 00:25 UTC, lucacome commented on docs/content/logging-and-monitoring/status-page.md
> +1. App Protect Dos: Open your browser at http://127.0.0.1:8080/dashboard-dos.html to access the dashboard.
```suggestion
1. App Protect DoS: Open your browser at http://127.0.0.1:8080/dashboard-dos.html to access the dashboard.
```

2022-12-21 00:25 UTC, lucacome commented on docs/content/logging-and-monitoring/status-page.md
> +**Note**: The [API](https://nginx.org/en/docs/http/ngx_http_api_module.html), which the dashboard uses to get the metrics, is also accessible: use the `/api` path. For App Protect Dos use the `/api/d
```suggestion
**Note**: The [API](https://nginx.org/en/docs/http/ngx_http_api_module.html), which the dashboard uses to get the metrics, is also accessible: use the `/api` path. For App Protect DoS use the `/api/dos` path. Note that the API is configured in the read-only mode.
```

2023-01-04 15:47 UTC, jjngx commented
@pasmant looks ok, could you please fill info required in the PR template, and description of performed tests?

2023-01-11 20:06 UTC, merged