fix: controller.topologySpreadConstraints schema
nginxinc/kubernetes-ingress pull request #3527
Opened 2023-02-07 11:49 UTC by marcuz

### Proposed changes
Fixes error:

```
controller.topologySpreadConstraints: Invalid type. Expected: object, given: array
```

Expected YAML:

```yaml
controller:
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app: nginx-ingress
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app: nginx-ingress
```

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

- [x] I have read the [CONTRIBUTING](https://github.com/nginxinc/kubernetes-ingress/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that all unit tests pass after adding my changes
- [x] I have updated necessary documentation
- [x] I have rebased my branch onto main
- [x] I will ensure my PR is targeting the main branch and pulling from my branch from my own fork

2023-02-07 11:57 UTC, vepatel approved these changes

2023-02-07 13:57 UTC, jjngx approved these changes

2023-02-07 19:22 UTC, lucacome requested changes
Hi @marcuz I think we just need to change the `ref` to the right definition and everything else can remain the same

2023-02-07 19:22 UTC, lucacome commented on deployments/helm-chart/values.schema.json
>            "$ref": "https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.25.4/_definitions.json#/definitions/io.k8s.api.core.v1.TopologySpreadConstraint"
```suggestion
          "$ref": "https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.25.4/_definitions.json#/definitions/io.k8s.api.core.v1.PodSpec/properties/topologySpreadConstraints"
```

2023-02-07 22:06 UTC, marcuz commented on deployments/helm-chart/values.schema.json
>            "$ref": "https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.25.4/_definitions.json#/definitions/io.k8s.api.core.v1.TopologySpreadConstraint"
Apologies, I missed that!

2023-02-07 23:49 UTC, lucacome commented on deployments/helm-chart/README.md
> +`controller.topologySpreadConstraints` | The topology spread constraints of the Ingress controller pods. | []
```suggestion
`controller.topologySpreadConstraints` | The topology spread constraints of the Ingress controller pods. | {}
```

2023-02-07 23:49 UTC, lucacome commented on deployments/helm-chart/values.schema.json
> +          "topologySpreadConstraints": [],
```suggestion
          "topologySpreadConstraints": {},
```

2023-02-07 23:49 UTC, lucacome commented on deployments/helm-chart/values.schema.json
> +        "topologySpreadConstraints": [],
```suggestion
        "topologySpreadConstraints": {},
```

2023-02-07 23:49 UTC, lucacome commented on deployments/helm-chart/values.yaml
> +  # topologySpreadConstraints: []
```suggestion
  # topologySpreadConstraints: {}
```

2023-02-08 09:56 UTC, marcuz commented
@lucacome sorry I totally misunderstood the behaviour of `$ref` here. Pushing a cleanup commit soon!

2023-02-08 10:03 UTC, marcuz commented
Just changing the `$ref` as suggested, lint passes successfully:

```
$ helm lint . -f values.yaml -f values-test.yaml 
==> Linting .

1 chart(s) linted, 0 chart(s) failed
```

`values-test.yaml` contains the `controller.topologySpreadConstraints` as specified above.

2023-02-08 23:45 UTC, lucacome approved these changes
Thanks @marcuz !

2023-02-09 01:27 UTC, merged

2023-02-09 08:15 UTC, marcuz commented
> Thanks @marcuz !

Sorry for all the back and forth. :smile:

2023-02-10 21:07 UTC, cpuengr949 commented
@lucacome I am getting this same error using terraform to build
`      topologySpreadConstraints = [
        {
          labelSelector = {
            matchLabels = {
              app = "nginx-plus-nginx-ingress"
            }
          }
          maxSkew           = 1
          topologyKey       = "kubernetes.io/hostname"
          whenUnsatisfiable = "DoNotSchedule"
         }
       ]
`
Which is creating the code
`                  "topologySpreadConstraints":
                  - "labelSelector":
                      "matchLabels":
                        "app": "nginx-plus-nginx-ingress"
                    "maxSkew": 1
                    "topologyKey": "kubernetes.io/hostname"
                    "whenUnsatisfiable": "DoNotSchedule"
`

2023-02-10 21:28 UTC, lucacome commented
@cpuengr949 even with the fix in this PR?

2023-02-10 21:32 UTC, cpuengr949 commented
@lucacome How do I get the fix? 
I believe terraform downloads it each time right?
Thank You

2023-02-10 22:09 UTC, lucacome commented
@cpuengr949 if it's pulling the `main` branch from here or using the `edge` helm chart, it should have the fix in this PR, but I don't know what your setup is 🙂