Inherit NET_BIND_SERVICE from IC to Nginx
nginxinc/kubernetes-ingress pull request #3722
Opened 2023-04-03 18:00 UTC by sigv

### Proposed changes

8be0144: _Rework port binding logic without privileges_ caused issues for host networking configurations. The Kubernetes documentation states that the `net.*` sysctls can be used with container networking, which was misinterpreted.

This commit reverts the change, bringing back NET_BIND_SERVICE to the Nginx process, as well as reverts the libcap package removal done in a later commit.

In order to avoid privilege escalation being re-introduced, the IC process is also receiving NET_BIND_SERVICE, so that it can be inherited over to Nginx.

This change aims to restore host networking as functional for the Helm chart. A future change is recommended to harden security for the IC process (to drop the capability after executing Nginx) as well as Nginx itself (to drop the capability after binding).

OBS! To use a 3.1.0 image, you should manually install the `setcap` binary and add `+ep` on `/nginx-ingress` and `+eip` on `nginx` binary.

Resolves #3714.
Effectively reverts #3573 and #3616.

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

- [x] I have read the [CONTRIBUTING](https://github.com/nginxinc/kubernetes-ingress/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that all unit tests pass after adding my changes
- [ ] I have updated necessary documentation
- [x] I have rebased my branch onto main
- [x] I will ensure my PR is targeting the main branch and pulling from my branch from my own fork

2023-04-03 18:08 UTC, tstraley commented
IMO this is a better solution anyway because the [Kubernetes Pod Security Standards](https://kubernetes.io/docs/concepts/security/pod-security-standards) allows for adding the `NET_BIND_SERVICE` capability within the [restricted policy](https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted), whereas the `sysctls` `net.ipv4.ip_unprivileged_port_start` is only permitted in the [baseline policy](https://kubernetes.io/docs/concepts/security/pod-security-standards/#baseline).

I _think_ this means NIC will be fully compatible with the restricted policy after this, if I'm not missing anything.

2023-04-03 18:12 UTC, sigv commented
> IMO this is a better solution anyway because the [Kubernetes Pod Security Standards](https://kubernetes.io/docs/concepts/security/pod-security-standards) allows for adding the `NET_BIND_SERVICE` capability within the [restricted policy](https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted), whereas the `sysctls` `net.ipv4.ip_unprivileged_port_start` is only permitted in the [baseline policy](https://kubernetes.io/docs/concepts/security/pod-security-standards/#baseline).
> 
> I _think_ this means NIC will be fully compatible with the restricted policy after this, if I'm not missing anything.

From what I see, `net.ipv4.ip_unprivileged_port_start` is allowed in Baseline policy as it is categorized as a safe sysctl.
However I am not seeing any mention of it being blocked in Restricted policy.

Keep in mind that Restricted policy inherits Baseline policy.

Am I missing something here?

2023-04-03 18:14 UTC, tstraley commented
> From what I see, `net.ipv4.ip_unprivileged_port_start` is allowed in Baseline policy as it is categorized as a safe sysctl. However I am not seeing any mention of it being blocked in Restricted policy.
> 
> Keep in mind that Restricted policy inherits Baseline policy.


Oh, I see - that wasn't clear to me. Thanks.

2023-04-03 18:16 UTC, sigv commented
> Oh, I see - that wasn't clear to me. Thanks.

The first line of Controls states _Everything from the baseline profile._
But I do agree the Documentation can be a tricky beast.

As to why this solution is objectively cleaner, it allows dropping the capability in turn locking down ports 80/443.

2023-04-03 20:37 UTC, sigv commented
`VirtualServerRoute.k8s.nginx.org` strangeness when running tests locally, not sure how this change could cause that.

```text
suite/test_v_s_route.py::TestVirtualServerRouteValidation::test_openapi_validation_flow[crd_ingress_controller0-v_s_route_setup0]
-------------------------------------------------------------------------------------- live log call ---------------------------------------------------------------------------------------
ERROR    root:vs_vsr_resources_utils.py:188 Failed with exception while patching VirtualServerRoute: backend2
Traceback (most recent call last):
  File "/home/azureuser/kubernetes-ingress/tests/suite/utils/vs_vsr_resources_utils.py", line 183, in patch_v_s_route_from_yaml
    custom_objects.patch_namespaced_custom_object(
  File "/home/azureuser/venv/lib/python3.10/site-packages/kubernetes/client/api/custom_objects_api.py", line 2941, in patch_namespaced_custom_object
    return self.patch_namespaced_custom_object_with_http_info(group, version, namespace, plural, name, body, **kwargs)  # noqa: E501
  File "/home/azureuser/venv/lib/python3.10/site-packages/kubernetes/client/api/custom_objects_api.py", line 3072, in patch_namespaced_custom_object_with_http_info
    return self.api_client.call_api(
  File "/home/azureuser/venv/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/home/azureuser/venv/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/home/azureuser/venv/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 407, in request
    return self.rest_client.PATCH(url,
  File "/home/azureuser/venv/lib/python3.10/site-packages/kubernetes/client/rest.py", line 296, in PATCH
    return self.request("PATCH", url,
  File "/home/azureuser/venv/lib/python3.10/site-packages/kubernetes/client/rest.py", line 235, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (422)
Reason: Unprocessable Entity
HTTP response headers: HTTPHeaderDict({'Audit-Id': '514ffa11-3d33-4614-bba9-425893ba7e42', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': 'f0b5ec4f-ce76-4ca2-abd4-790b16e418db', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'e3033d16-6204-451c-8cb3-8fe069cde889', 'Date': 'Mon, 03 Apr 2023 20:32:48 GMT', 'Content-Length': '584'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"VirtualServerRoute.k8s.nginx.org \"backend2\" is invalid: spec.subroutes[0].action.pass: Invalid value: \"integer\": spec.subroutes[0].action.pass in body must be of type string: \"integer\"","reason":"Invalid","details":{"name":"backend2","group":"k8s.nginx.org","kind":"VirtualServerRoute","causes":[{"reason":"FieldValueTypeInvalid","message":"Invalid value: \"integer\": spec.subroutes[0].action.pass in body must be of type string: \"integer\"","field":"spec.subroutes[0].action.pass"}]},"code":422}
```

2023-04-03 20:50 UTC, sigv commented
It seems the edge image is failing `VirtualServerRoute.k8s.nginx.org` tests when I run it, and so is my local testing. Looks good otherwise.

2023-04-04 09:01 UTC, sigv commented
I did a rebase, and it looks fine, but Github reports that this PR consists of three commits now. I think that's a Github web UI bug, but let me know if I should try rebasing again.

2023-04-04 11:21 UTC, sigv commented
Heads up - the CI failed on

- `debian`: `The repository 'https://pkgs.nginx.com/plus/R28/debian bullseye Release' does not have a Release file.`
- `alpine`: `Ignoring https://pkgs.nginx.com/plus/R28/alpine/v3.17/main: Protocol error`

2023-04-26 11:35 UTC, sigv commented
@vepatel, heads up, the Plus repository seems to be unavailable on the CI run!

2023-04-27 09:05 UTC, ciarams87 approved these changes

2023-04-27 11:35 UTC, jjngx approved these changes

2023-04-28 07:07 UTC, lucacome requested changes

2023-04-28 09:46 UTC, sigv commented on build/Dockerfile
> +RUN --mount=type=bind,target=/tmp setcap 'cap_net_bind_service=+ep' /nginx-ingress && setcap -v 'cap_net_bind_service=+ep' /nginx-ingress
Dropped `--mount=type=bind,target=/tmp` from all the `RUN setcap` instructions.

2023-04-28 09:51 UTC, sigv commented on build/Dockerfile
> +RUN --mount=type=bind,target=/tmp setcap 'cap_net_bind_service=+ep' /nginx-ingress && setcap -v 'cap_net_bind_service=+ep' /nginx-ingress
Move the `setcap` call out from `builder` to `container` as requested. ✔️

2023-04-28 11:37 UTC, sigv commented
Still hitting issues in CI for accessing the Nginx Plus repository. :/

----

- [Helm Tests (debian-plus, plus)](https://github.com/nginxinc/kubernetes-ingress/actions/runs/4829317490/jobs/8605275765?pr=3722#step:5:469)
- [Smoke Tests (debian-plus, vs, 1.27.1)](https://github.com/nginxinc/kubernetes-ingress/actions/runs/4829317490/jobs/8605300049?pr=3722#step:3:642)
- [Smoke Tests (debian-plus, ts, 1.27.1)](https://github.com/nginxinc/kubernetes-ingress/actions/runs/4829317490/jobs/8605300130?pr=3722#step:3:651)
- [Smoke Tests (debian-plus-nap, dos, 1.27.1)](https://github.com/nginxinc/kubernetes-ingress/actions/runs/4829317490/jobs/8605300489?pr=3722#step:3:654)
- [Smoke Tests (debian-plus-nap, appprotect, 1.27.1)](https://github.com/nginxinc/kubernetes-ingress/actions/runs/4829317490/jobs/8605300590?pr=3722#step:3:668)
```text
E: The repository 'https://pkgs.nginx.com/plus/R28/debian bullseye Release' does not have a Release file.
```

----

- [Smoke Tests (alpine-plus, ingresses, 1.27.1)](https://github.com/nginxinc/kubernetes-ingress/actions/runs/4829317490/jobs/8605300214?pr=3722#step:3:439)
- [Smoke Tests (alpine-plus, vsr, 1.27.1)](https://github.com/nginxinc/kubernetes-ingress/actions/runs/4829317490/jobs/8605300303?pr=3722#step:3:443)
```text
WARNING: Ignoring https://pkgs.nginx.com/plus/R28/alpine/v3.17/main: Protocol error
ERROR: unable to select packages:
  nginx-plus (no such package):
    required by: world[nginx-plus]
  nginx-plus-module-njs (no such package):
    required by: world[nginx-plus-module-njs]
  nginx-plus-module-opentracing (no such package):
    required by: world[nginx-plus-module-opentracing]
```

----

All of these jobs report warnings for `nginx-repo.tls` secrets at start of test run:
```text
Warning: nginx-repo.crt= is not a valid secret
Warning: nginx-repo.key= is not a valid secret
```

And there is [Smoke Tests (debian-plus-nap, dos, 1.27.1)](https://github.com/nginxinc/kubernetes-ingress/actions/runs/4829317490/jobs/8605300489?pr=3722#step:3:652) which also reports issue with reading the data:
```
  Could not load client certificate (/etc/ssl/nginx/nginx-repo.crt, SslCert option) or key (/etc/ssl/nginx/nginx-repo.key, SslKey option): Error while reading file. [IP: 52.59.52.27 443]
```

2023-04-28 11:38 UTC, sigv commented
@ciarams87 ping ☝🏻

2023-04-28 11:54 UTC, ciarams87 commented
> Still hitting issues in CI for accessing the Nginx Plus repository. 😕
> 
> * [Helm Tests (debian-plus, plus)](https://github.com/nginxinc/kubernetes-ingress/actions/runs/4829317490/jobs/8605275765?pr=3722#step:5:469)
> * [Smoke Tests (debian-plus, vs, 1.27.1)](https://github.com/nginxinc/kubernetes-ingress/actions/runs/4829317490/jobs/8605300049?pr=3722#step:3:642)
> * [Smoke Tests (debian-plus, ts, 1.27.1)](https://github.com/nginxinc/kubernetes-ingress/actions/runs/4829317490/jobs/8605300130?pr=3722#step:3:651)
> * [Smoke Tests (debian-plus-nap, dos, 1.27.1)](https://github.com/nginxinc/kubernetes-ingress/actions/runs/4829317490/jobs/8605300489?pr=3722#step:3:654)
> * [Smoke Tests (debian-plus-nap, appprotect, 1.27.1)](https://github.com/nginxinc/kubernetes-ingress/actions/runs/4829317490/jobs/8605300590?pr=3722#step:3:668)
> 
> ```
> E: The repository 'https://pkgs.nginx.com/plus/R28/debian bullseye Release' does not have a Release file.
> ```
> 
>  * [Smoke Tests (alpine-plus, ingresses, 1.27.1)](https://github.com/nginxinc/kubernetes-ingress/actions/runs/4829317490/jobs/8605300214?pr=3722#step:3:439)
> * [Smoke Tests (alpine-plus, vsr, 1.27.1)](https://github.com/nginxinc/kubernetes-ingress/actions/runs/4829317490/jobs/8605300303?pr=3722#step:3:443)
> 
> ```
> WARNING: Ignoring https://pkgs.nginx.com/plus/R28/alpine/v3.17/main: Protocol error
> ERROR: unable to select packages:
>   nginx-plus (no such package):
>     required by: world[nginx-plus]
>   nginx-plus-module-njs (no such package):
>     required by: world[nginx-plus-module-njs]
>   nginx-plus-module-opentracing (no such package):
>     required by: world[nginx-plus-module-opentracing]
> ```
> 
> All of these jobs report warnings for `nginx-repo.tls` secrets at start of test run:
> 
> ```
> Warning: nginx-repo.crt= is not a valid secret
> Warning: nginx-repo.key= is not a valid secret
> ```
> 
> While most Debian runs have a generic "could not get a Release file" error.. There is [Smoke Tests (debian-plus-nap, dos, 1.27.1)](https://github.com/nginxinc/kubernetes-ingress/actions/runs/4829317490/jobs/8605300489?pr=3722#step:3:652) which also reports issue with reading the secret data:
> 
> ```
>   Could not load client certificate (/etc/ssl/nginx/nginx-repo.crt, SslCert option) or key (/etc/ssl/nginx/nginx-repo.key, SslKey option): Error while reading file.
> ```

@sigv Running the pipeline again now. Sorry for the inconvenience! 

(As an explanation, PRs from external contributors cannot access the build secrets. If there are no changes to the base NGINX Plus images, this normally does not cause a problem as we can use cached layers from other builds, but when changes are made which require rebuilding the whole image, as here, a maintainer needs to open a separate branch which does have secret-read access)

2023-04-28 20:18 UTC, lucacome approved these changes
Thanks @sigv !

2023-04-28 20:19 UTC, merged

2023-11-29 07:32 UTC, muhammadwasay commented
@sigv I am confused after reading all the comments. Just want to confirm that can nginxinc/kubernetes-ingress avoid the privilege escalation of NET_BIND_SERVICE or not?