Docs theme updates
nginxinc/kubernetes-ingress pull request #3751
Opened 2023-04-11 21:55 UTC by jputrino

### Proposed changes

This PR changes the configurations for the docs theme. We have moved the theme development to GitHub so it will be accessible in Netlify builds (and the _vendors directory is no longer required). The changes in this PR also let us manage future theme bumps by updating the NGINX_THEME_VERSION variable stored in the Netlify console.

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

- [ ] I have read the [CONTRIBUTING](https://github.com/nginxinc/kubernetes-ingress/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that all unit tests pass after adding my changes
- [ ] I have updated necessary documentation
- [ ] I have rebased my branch onto main
- [ ] I will ensure my PR is targeting the main branch and pulling from my branch from my own fork

2023-04-11 22:09 UTC, lucacome approved these changes
This is awesome! 🚀

2023-04-12 08:20 UTC, ciarams87 approved these changes
🤩 🚀

2023-04-12 10:29 UTC, tomasohaodha requested changes

2023-04-12 10:29 UTC, tomasohaodha commented on docs/Makefile
> +# Builds using the Hugo "staging" environment
Typo - should be "production" environment

2023-04-12 20:01 UTC, jputrino commented on docs/Makefile
> +# Builds using the Hugo "staging" environment
good catch! fixed

2023-04-14 08:07 UTC, tomasohaodha approved these changes

2023-04-14 08:08 UTC, merged