Update JWT install guide
nginxinc/kubernetes-ingress pull request #3884
Opened 2023-05-08 20:31 UTC by jasonwilliams14

### Proposed changes
This is an update to the JWT token method to install NGINX Ingress controller, providing a  more detailed walkthrough.

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

- [x ] I have read the [CONTRIBUTING](https://github.com/nginxinc/kubernetes-ingress/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ x] I have checked that all unit tests pass after adding my changes
- [ x] I have updated necessary documentation
- [ x] I have rebased my branch onto main
- [ x] I will ensure my PR is targeting the main branch and pulling from my branch from my own fork

2023-05-08 23:28 UTC, dreesf5 requested changes
I tested both via sources and manifest and both worked now.  Small things to make it a bit more readable. 

I'd also be more clear about how and when to use the namespace -n nginx-ingress.

2023-05-08 23:28 UTC, dreesf5 commented on docs/content/installation/using-the-jwt-token-docker-secret.md
> +2. Log into MyF5 portal. [MyF5 portal login](https://myf5.com/ "MyF5 portal login")
Perhaps give more description here.  Something like:  You'll find the token under the "Subscription Detail" section of your subscription.

2023-05-08 23:28 UTC, dreesf5 commented on docs/content/installation/using-the-jwt-token-docker-secret.md
> +   You can `cat` the contents of the JWT token and then store the output to use in the following steps. Make sure that there are no additional characters or extra whiespace that might have been accid
s/broke/brake/.  Extra whitespace in prevent.

2023-05-08 23:28 UTC, dreesf5 commented on docs/content/installation/using-the-jwt-token-docker-secret.md
> +3. Specify a `imagePullSecrets` to pull from the private registry.
imagePullSecretName

2023-05-08 23:28 UTC, dreesf5 commented on docs/content/installation/using-the-jwt-token-docker-secret.md
> +
You should then write out the command line one would use for the manifests.

```bash
helm install my-release -n nginx-ingress -f values.yaml .
```

2023-05-17 22:11 UTC, dreesf5 commented on docs/content/installation/using-the-jwt-token-docker-secret.md
> +### Specify the `imagePullSecrets`
I would update this to `imagePullSecretName` as well.  Sorry I missed it the first time.

2023-05-18 13:59 UTC, brianehlert commented on docs/content/installation/using-the-jwt-token-docker-secret.md
> +### Using the `helm` charts method:
Is this an alternate Helm install method that is different than what begins on line 70?
Line 70 represents itself as THE Helm install method.  So it is kind of confusing to the novice to have this insert itself in as something that is different without much explanation.

Maybe an explanation like:  "Helm also supports overriding or defining values using the command line.  If you have an existing values files and want to override or test this method before committing to values files changes, you can insert the necessary values using the following single command line option."

2023-05-18 14:05 UTC, dreesf5 requested changes

2023-05-18 14:05 UTC, dreesf5 commented on docs/content/installation/using-the-jwt-token-docker-secret.md
>      ]
Did you really intend to change these to 3.1.0?

2023-06-23 13:57 UTC, ADubhlaoich approved these changes
I have made numerous rewrites in this PR to improve the readability of the page: it will need an additional once-over at the minimum to ensure that the instructions are accurate.

2023-07-12 10:52 UTC, haywoodsh approved these changes

2023-08-15 14:08 UTC, dreesf5 approved these changes

2023-08-17 18:06 UTC, merged