Update README
nginxinc/kubernetes-ingress pull request #4044
Opened 2023-06-22 22:44 UTC by lucacome

### Proposed changes
Changes:
- Removes survey link
- Adds a couple of badges
- Move description of NIC at the top

2023-06-22 22:53 UTC, brianehlert requested changes

2023-06-22 22:53 UTC, brianehlert commented on README.md
>  This repo provides an implementation of an Ingress Controller for NGINX and NGINX Plus.
This repo provides an implementation of an Ingress Controller for NGINX and NGINX Plus from the people behind NGINX.

2023-06-23 17:07 UTC, brianehlert approved these changes

2023-06-23 23:49 UTC, jasonwilliams14 approved these changes
looks good

2023-06-23 23:56 UTC, merged