Release 3.2.0
nginxinc/kubernetes-ingress pull request #4055
Opened 2023-06-24 01:39 UTC by lucacome

### Proposed changes
Update docs for 3.2.0 release

2023-06-26 08:06 UTC, shaun-nx approved these changes

2023-06-26 09:18 UTC, jjngx approved these changes

2023-06-26 11:21 UTC, ADubhlaoich approved these changes
LGTM!

2023-06-26 14:34 UTC, brianehlert requested changes

2023-06-26 14:34 UTC, brianehlert commented on docs/content/releases.md
> +
We should add a line about license tracking, even though it is delivered separate.  
The linked PR can be the doc.
"Added utilization tracking for supported (paid) customers"

2023-06-26 14:34 UTC, brianehlert commented on docs/content/releases.md
> +
There should be a mention of Google marketplace, even though it is not complete.

2023-06-26 14:34 UTC, brianehlert commented on docs/content/releases.md
> +* [4031](https://github.com/nginxinc/kubernetes-ingress/pull/4031) Add Alpine image with FIPS inside.
This should mention it is for "supported (paid) customers"

2023-06-27 16:10 UTC, brianehlert commented on docs/content/releases.md
> +
We should mention the new doc for how to customize OIDC using config map.

2023-06-27 18:35 UTC, merged