Add automated tests for custom vs listeners
nginxinc/kubernetes-ingress pull request #4311
Opened 2023-08-31 10:51 UTC by haywoodsh

### Proposed changes

Describe the use case and detail of the change. If this PR addresses an issue on GitHub, make sure to include a link to
that issue here in this description (not in the title of the PR).

### Checklist

Before creating a PR, run through this checklist and mark each as complete.

- [ ] I have read the [CONTRIBUTING](https://github.com/nginxinc/kubernetes-ingress/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that all unit tests pass after adding my changes
- [ ] I have updated necessary documentation
- [ ] I have rebased my branch onto main
- [ ] I will ensure my PR is targeting the main branch and pulling from my branch from my own fork

2023-09-04 11:41 UTC, vepatel approved these changes

2023-09-04 12:31 UTC, shaun-nx requested changes

2023-09-04 12:31 UTC, shaun-nx commented on tests/suite/test_virtual_server_custom_listeners.py
> +        assert "listen [::]:443;" not in vs_config
```suggestion
        assert "listen 443 ssl;" not in vs_config
        assert "listen [::]:443 ssl;" not in vs_config
```

2023-09-04 12:31 UTC, shaun-nx commented on tests/suite/test_virtual_server_custom_listeners.py
> +        assert "listen [::]:443;" not in vs_config
```suggestion
        assert "listen 443 ssl;" not in vs_config
        assert "listen [::]:443 sll;" not in vs_config
```

2023-09-05 09:50 UTC, shaun-nx approved these changes
👍

2023-09-05 13:40 UTC, vepatel commented on tests/suite/test_virtual_server_custom_listeners.py
> +            if expected_response > 0:
iterable type(string) to int needed

2023-09-05 13:45 UTC, vepatel commented on tests/suite/test_virtual_server_custom_listeners.py
> +        for expected_response, url in zip(urls, [404, 404, 200, 200]):
```suggestion
        for url, expected_response in zip(urls, [404, 404, 200, 200]):
```
@haywoodsh

2023-09-05 15:02 UTC, vepatel approved these changes

2023-09-05 15:28 UTC, merged