Add documentation for deploying prometheus service monitor using Helm
nginxinc/kubernetes-ingress pull request #4398
Opened 2023-09-20 16:14 UTC by shaun-nx

### Proposed changes

This PR adds a new document to demonstrate how to create a ServiceMonitor resource using Helm to allow Prometheus metrics to be captured using a Prometheus resource.

### Checklist

Before creating a PR, run through this checklist and mark each as complete.

- [ ] I have read the [CONTRIBUTING](https://github.com/nginxinc/kubernetes-ingress/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that all unit tests pass after adding my changes
- [ ] I have updated necessary documentation
- [ ] I have rebased my branch onto main
- [ ] I will ensure my PR is targeting the main branch and pulling from my branch from my own fork

2023-09-21 14:17 UTC, vepatel approved these changes

2023-09-21 15:28 UTC, ADubhlaoich approved these changes
Approved, but made a bunch of edit suggestions. There should only be one h1 heading in a page, which is the page title - so all other headings should be h2 (`##`) maximum.

Most of the edit suggestions are to clarify language or make the text itself more concise.

2023-09-21 15:28 UTC, ADubhlaoich commented on docs/content/logging-and-monitoring/prometheus-servicemonitor.md
> +title: Prometheus
```suggestion
title: Prometheus and ServiceMonitor
```

2023-09-21 15:28 UTC, ADubhlaoich commented on docs/content/logging-and-monitoring/prometheus-servicemonitor.md
> +
```suggestion
```

2023-09-21 15:28 UTC, ADubhlaoich commented on docs/content/logging-and-monitoring/prometheus-servicemonitor.md
> +description: "Exposing Prometheus metrics using ServiceMonitor."
```suggestion
description: "This document describes how to expose Prometheus metrics using ServiceMonitor for the F5 NGINX Ingress Controller."
```

2023-09-21 15:28 UTC, ADubhlaoich commented on docs/content/logging-and-monitoring/prometheus-servicemonitor.md
> +
```suggestion

<br>

```

2023-09-21 15:28 UTC, ADubhlaoich commented on docs/content/logging-and-monitoring/prometheus-servicemonitor.md
> +The `ServiceMonitor` resource will describe the target `Service` to be monitored by a `Prometheus` resource.
```suggestion
This page describes how to use Helm with NGINX Ingress Controller to deploy a Prometheus `ServiceMonitor` resource, using it to monitor a target `Service` with the `Prometheus` resource.
```

2023-09-21 15:28 UTC, ADubhlaoich commented on docs/content/logging-and-monitoring/prometheus-servicemonitor.md
> +```
```suggestion
## Prerequisites
* A working [Prometheus resource or Prometheus Operator](https://prometheus-operator.dev/docs/user-guides/getting-started/)
* The latest ServiceMonitor CRD from the [prometheus-operator](https://github.com/prometheus-operator/prometheus-operator) repository:
```shell
LATEST=$(curl -s https://api.github.com/repos/prometheus-operator/prometheus-operator/releases/latest | jq -cr .tag_name)
curl https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/$LATEST/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml | kubectl create -f -
```
```

2023-09-21 15:28 UTC, ADubhlaoich commented on docs/content/logging-and-monitoring/prometheus-servicemonitor.md
> +To configure a `ServiceMonitor` resource with your Helm to installation, set the following paramaters:
```suggestion
## Installation
To configure a `ServiceMonitor` resource with your existing Helm installation, set the following parameters:
```

2023-09-21 15:28 UTC, ADubhlaoich commented on docs/content/logging-and-monitoring/prometheus-servicemonitor.md
> +2. A `ServiceMonitor` resource configured to monitor the service exposing the metrics.
```suggestion
These changes will:
1. Create a  `Service` to expose Prometheus metrics from NGINX Ingress Controller on port `9113`.
2. Create a `ServiceMonitor` resource configured to monitor the Service exposing the metrics.
```

2023-09-21 15:28 UTC, ADubhlaoich commented on docs/content/logging-and-monitoring/prometheus-servicemonitor.md
> +The value of this label **must** match the value of `serviceMonitorSelector.matchLabels` in your `Prometheus` resource.
```suggestion
{{< note >}} The parameter for `prometheus.serviceMonitor.labels` can be set to any custom value, but it **must** match the value of `serviceMonitorSelector.matchLabels` in your `Prometheus` resource. {{< /note >}} 
```

2023-09-21 15:28 UTC, ADubhlaoich commented on docs/content/logging-and-monitoring/prometheus-servicemonitor.md
> +These YAML files are used to visualise what these configurations look like after deployment.
```suggestion
## Example YAML Files
```

I think the fact they are labelled examples is sufficient: there is no need to explain what an example actually is or indicates.

2023-09-21 15:28 UTC, ADubhlaoich commented on docs/content/logging-and-monitoring/prometheus-servicemonitor.md
> +Example `ServiceMonitor` resource YAML:
```suggestion
### Example ServiceMonitor and Service YAML
**`ServiceMonitor` Example**:
```

2023-09-21 15:28 UTC, ADubhlaoich commented on docs/content/logging-and-monitoring/prometheus-servicemonitor.md
> +Example `Service` resource YAML:
```suggestion
**`Service` Example**:
```

2023-09-21 15:28 UTC, ADubhlaoich commented on docs/content/logging-and-monitoring/prometheus-servicemonitor.md
> +## Example Prometheus resource YAML
```suggestion
### Example Prometheus YAML
```

2023-09-21 15:28 UTC, ADubhlaoich commented on docs/content/logging-and-monitoring/prometheus-servicemonitor.md
> +If you have a `Prometheus` resource deployed capture the `ServiceMonitor` resource, the YAML of that file will look something like this:
```suggestion
To add a  `Prometheus` resource to capture the `ServiceMonitor` resource, the YAML will look like the following:
```

2023-09-21 15:34 UTC, ADubhlaoich commented on docs/content/logging-and-monitoring/prometheus-servicemonitor.md
> +2. A `ServiceMonitor` resource configured to monitor the service exposing the metrics.
The very first instance of any NGINX product name on any documentation page is supposed to include the F5 prefix for legal branding purposes. I've been lazy about suggesting or enforcing it for a while, but the change is being made across the entire documentation set at the moment.

We also avoid 'the Ingress Controller': in context it's usually "the NGINX Ingress Controller" or "an NGINX Ingress Controller instance".

2023-09-21 22:10 UTC, lucacome requested changes
Can this just be a section in the Prometheus doc we already have? I'm not sure we even need to show the yaml files since this is all through helm...

2023-09-22 08:08 UTC, vepatel commented
@lucacome not all the yamls in example are managed by helm.

2023-09-22 08:57 UTC, shaun-nx commented
@lucacome I see what you mean. It could make more sense for it to existing along side our current prometheus doc.

As for the example Yaml files, I wanted them there just to help visualise what the resources looked like (i.e. the labels and how those labels related to eachother)

2023-09-22 16:35 UTC, jasonwilliams14 commented
> As for the example Yaml files, I wanted them there just to help visualise what the resources looked like (i.e. the labels and how those labels related to eachother)

@shaun-nx what about using the graphic I initially created to show the correlation between the labels, and how they connect to each other?

https://github.com/nginxinc/kubernetes-ingress/issues/4210#issuecomment-1679380507

that seemed to resonate well from a visualization point of view.
thoughts?

2023-09-25 13:13 UTC, shaun-nx commented
Added steps to an individual doc instead. Thanks again for the suggestion @lucacome it really did make a lot more sense.

@jasonwilliams14 I think for that Diagram, it would be better if we add that to a new doc that shows an end-to-end use case of deploying a Prometheus Operator and also deploying NIC with a ServerMonitor resource. A doc like that could exist in the tutorial section. I think for now these steps will do to ensure users know the options available.

2023-09-25 13:13 UTC, closed without merging