Add string comparison functions to Go template executors
nginxinc/kubernetes-ingress pull request #4560
Opened 2023-10-24 15:26 UTC by ianyong

### Proposed changes

Add the following helper functions to the Go template executors to enable string comparisons:
* `contains` - [`strings.Contains`](https://pkg.go.dev/strings#Contains)
* `hasPrefix` - [`strings.HasPrefix`](https://pkg.go.dev/strings#HasPrefix)
* `hasSuffix` - [`strings.HasSuffix`](https://pkg.go.dev/strings#HasSuffix)
* `toLower` - [`strings.ToLower`](https://pkg.go.dev/strings#ToLower)
* `toUpper` - [`strings.ToUpper`](https://pkg.go.dev/strings#ToUpper)

Not very sure why there are two versions of the template executors. I presume `version1` will eventually be phased out in favour of `version2` given the naming? Either way, I've made the same changes to both versions.

Resolves #4555. 

### Checklist

Before creating a PR, run through this checklist and mark each as complete.

- [x] I have read the [CONTRIBUTING](https://github.com/nginxinc/kubernetes-ingress/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that all unit tests pass after adding my changes
- [x] I have updated necessary documentation
- [x] I have rebased my branch onto main
- [x] I will ensure my PR is targeting the main branch and pulling from my branch from my own fork

2023-10-24 15:30 UTC, ianyong commented on internal/configs/version2/template_helper.go
> -}
I removed this function because all it does it call `strings.ToLower` with the exact same parameters, which is unnecessary.

2023-10-24 16:37 UTC, jjngx requested changes
Thank you for contributing! Could you please keep tests in the same style as tests other packages in the project?

- call `t.Parallel()` as a first line in a test
- use anonymous struct literals for table tests (as in other test files)
- keep test struct fields not exported

2023-10-24 17:20 UTC, ianyong commented
@jjngx Thanks for reviewing! I've made the changes for the first 2 points. For the last point, the test struct fields need to be exported for them to be accessed within the templates, else the tests will fail with `<struct field name> is an unexported field of struct type struct <struct type>`. It's also why the `expected` struct field is not exported across all the test cases - because it does not need to be accessed within the templates.

2023-10-24 17:27 UTC, jjngx approved these changes
@ianyong thank you again for contributing! 🚀

2023-10-24 18:49 UTC, jjngx commented
@ianyong could you please update and push your branch?

2023-10-25 13:16 UTC, jjngx approved these changes

2023-11-01 11:07 UTC, ianyong commented
Is there anything I can do to get this PR merged? The failing CI jobs don't seem to be caused by my changes, or at least I see other PRs with the same failed jobs being merged.

2023-11-01 11:23 UTC, vepatel commented
@hanyouqing we'll prioritise merging this in coming week, thanks! You can monitor the state from parent issue.

2023-11-03 10:10 UTC, jjngx commented
@ianyong could you please update and push your branch?

2023-11-07 11:17 UTC, jjngx commented
@ianyong  could you please update and push your branch?

2023-11-07 11:25 UTC, shaun-nx approved these changes
👍

2023-11-07 12:33 UTC, haywoodsh approved these changes

2023-11-07 14:24 UTC, merged